#!/usr/bin/python3

"""Get MP3 links from a songspk.city album URL.

Examples:

    songspk http://songspk.city/indian-pops-remix/mtv-unplugged-season-5-multi-artists-2015.html
"""

import sys

import pyquery


def get_links_from_track_page(track_url):
    pq = pyquery.PyQuery(url=track_url)

    for link in pq('div.download-trget a'):
        href = link.get('href')
        if href.endswith('mp3'):
            print(href)


def get_links_from_albums_page(album_url):
    pq = pyquery.PyQuery(url=album_url)

    for link in pq('div.download-trget a'):
        href = link.get('href')
        if '/songspk.city/downloads/' in href:
            get_links_from_track_page(href)


if __name__ == '__main__':
    get_links_from_albums_page(sys.argv[1])
