#!/usr/bin/python3

"""Get MP3 links from a songspk.city album URL.

Examples:

    songspk http://songspk.city/indian-pops-remix/mtv-unplugged-season-5-multi-artists-2015.html
"""

import sys
import urllib.parse

from multiprocessing.pool import ThreadPool

import pyquery


def url_fix(url):
    scheme, netloc, path, qs, anchor = urllib.parse.urlsplit(url)
    path = urllib.parse.quote(path, '/%')
    qs = urllib.parse.quote_plus(qs, ':&=')
    return urllib.parse.urlunsplit((scheme, netloc, path, qs, anchor))


def get_links_from_page(page_url):
    pq = pyquery.PyQuery(url=page_url)
    return [url_fix(a.get('href')) for a in pq('div.download-trget a')]


def get_links_from_albums_page(album_url):
    urls = [
        url for url in get_links_from_page(album_url)
        if '/songspk.city/downloads/' in url
    ]

    pool = ThreadPool(processes=10)
    for result in pool.imap_unordered(get_links_from_page, urls):
        print("\n".join((url for url in result if url.endswith('.mp3'))))

if __name__ == '__main__':
    get_links_from_albums_page(sys.argv[1])
