#!/usr/bin/python3

"""Get MP3 links from a songspk.city album URL.

Examples:

    songspk http://songspk.city/indian-pops-remix/mtv-unplugged-season-5-multi-artists-2015.html
"""

import sys
import urllib.parse

from multiprocessing.pool import ThreadPool

import pyquery


def url_fix(url):
    scheme, netloc, path, qs, anchor = urllib.parse.urlsplit(url)
    path = urllib.parse.quote(path, '/%')
    qs = urllib.parse.quote_plus(qs, ':&=')
    return urllib.parse.urlunsplit((scheme, netloc, path, qs, anchor))


def get_links_from_track_page(track_url):
    pq = pyquery.PyQuery(url=track_url)

    for link in pq('div.download-trget a'):
        href = link.get('href')
        if href.endswith('mp3'):
            return href


def get_links_from_albums_page(album_url):
    pq = pyquery.PyQuery(url=album_url)

    urls = []

    for link in pq('div.download-trget a'):
        href = link.get('href')
        if '/songspk.city/downloads/' in href:
            urls.append(href)

    pool = ThreadPool(processes=10)
    results = pool.map(get_links_from_track_page, urls)

    for url in results:
        print(url_fix(url))

if __name__ == '__main__':
    get_links_from_albums_page(sys.argv[1])
