#!/usr/bin/python3

"""Get Video links from a Youtube Playlist URL.

The output is in a format that can be fed into youtube-dl via the -a switch.

Examples:

    ytb-links https://www.youtube.com/playlist?list=PL8B24C31197EC371C

    ytb-links https://www.youtube.com/playlist?list=PL8B24C31197EC371C > playlist

    You can then manually edit the playlist file and comment videos that you
    don't want to download. After you're done just pass the list to youtube-dl

    youtube-dl -a playlist
"""

import re
import sys
import pyquery


def get_video_links(playlist_url):
    pq = pyquery.PyQuery(url=playlist_url)
    for link in pq('td.pl-video-title > a'):
        print('# ' + link.text.strip())
        url = re.sub(r'&list=[\w-]+', '', link.get('href'))
        print('https://youtube.com' + url)
        print()


if __name__ == '__main__':
    get_video_links(sys.argv[1])
